import os
import pandas as pd
from pathlib import Path
from PIL import Image
import streamlit as st

from grid_determination_bizom.constant import VIZ_DIR, ALL_COLS

st.set_page_config(page_title="Grid Quality Viewer", layout="wide")

IMAGE_DIR = Path(__file__).parent / "data" / "delhi_grid_images"
CSV_PATH = VIZ_DIR


@st.cache_data
def load_data():
    df = pd.read_csv(CSV_PATH)

    if "predicted potential" in df.columns:
        df["potential_category"] = df["predicted potential"].str.title()
    else:
        st.error(
            "'predicted potential' column missing. Please ensure you are loading a CSV generated by the new 2-stage clustering pipeline."
        )
        st.stop()

    return df


df = load_data()

if "current_category" not in st.session_state:
    st.session_state.current_category = None

if "current_index" not in st.session_state:
    st.session_state.current_index = 0

st.title("Hyperlocal Grid Quality Viewer")
st.markdown(
    "Explore static map images alongside their spatial features and computed business potential."
)

st.subheader("Select a Category to Explore")
col_btn1, col_btn2, col_btn3 = st.columns(3)

if col_btn1.button("Low Potential", use_container_width=True):
    st.session_state.current_category = "Low Potential"
    st.session_state.current_index = 0

if col_btn2.button("Medium Potential", use_container_width=True):
    st.session_state.current_category = "Medium Potential"
    st.session_state.current_index = 0

if col_btn3.button("High Potential", use_container_width=True):
    st.session_state.current_category = "High Potential"
    st.session_state.current_index = 0

st.divider()

search_grid_id = st.text_input("Search by Grid ID (e.g., 221):", "")
if search_grid_id:
    try:
        search_id = int(search_grid_id)
        if search_id in df["grid_id"].values:
            target_row = df[df["grid_id"] == search_id].iloc[0]
            target_category = target_row["potential_category"]

            st.session_state.current_category = target_category
            category_df = df[df["potential_category"] == target_category].reset_index(
                drop=True
            )
            target_idx = category_df[category_df["grid_id"] == search_id].index[0]
            st.session_state.current_index = target_idx
        else:
            st.warning(f"Grid ID {search_id} not found in the dataset.")
    except ValueError:
        st.warning("Please enter a valid numeric Grid ID.")

if st.session_state.current_category is None:
    st.info(
        "Please select a potential category from the buttons above or search for a Grid ID to begin."
    )
else:
    current_df = df[
        df["potential_category"] == st.session_state.current_category
    ].reset_index(drop=True)
    total_items = len(current_df)

    if st.session_state.current_index >= total_items:
        st.session_state.current_index = total_items - 1
    elif st.session_state.current_index < 0:
        st.session_state.current_index = 0

    row_data = current_df.iloc[st.session_state.current_index]
    current_grid_id = row_data["grid_id"]

    col_nav1, col_nav2, col_nav3 = st.columns([1, 2, 1])

    with col_nav1:
        if (
            st.button("Previous", use_container_width=True)
            and st.session_state.current_index > 0
        ):
            st.session_state.current_index -= 1
            st.rerun()

    with col_nav2:
        st.markdown(
            f"<h4 style='text-align: center;'>Viewing: {st.session_state.current_category} | Grid ID: {current_grid_id}</h4>",
            unsafe_allow_html=True,
        )
        st.markdown(
            f"<p style='text-align: center;'>Image {st.session_state.current_index + 1} of {total_items}</p>",
            unsafe_allow_html=True,
        )

    with col_nav3:
        if (
            st.button("Next", use_container_width=True)
            and st.session_state.current_index < total_items - 1
        ):
            st.session_state.current_index += 1
            st.rerun()

    st.write("")
    col_img, col_data = st.columns([1.2, 1])
    with col_img:
        st.subheader("Satellite View")
        image_name = f"grid_{current_grid_id}.png"
        image_path = os.path.join(IMAGE_DIR, image_name)

        if os.path.exists(image_path):
            img = Image.open(image_path)
            st.image(img, caption=image_name, use_container_width=True)
        else:
            st.error(f"Image not found at path: \n`{image_path}`")
            st.markdown(
                """
                <div style="height: 400px; width: 100%; display: flex; align-items: center; justify-content: center; background-color: #f0f2f6; border-radius: 10px; border: 2px dashed #ccc;">
                    <p style="color: #666; font-size: 18px;">Image Unavailable</p>
                </div>
                """,
                unsafe_allow_html=True,
            )

    with col_data:
        st.subheader("Grid Features")

        m_col1, m_col2 = st.columns(2)
        m_col1.metric(
            "Kirana Potential Index",
            round(row_data.get("kirana_potential_index", 0), 2),
        )
        m_col2.metric(
            "Total Building Density",
            round(row_data.get("total_building_density", 0), 2),
        )

        m_col3, m_col4 = st.columns(2)
        m_col3.metric(
            "Yellow Bldgs (Count)", int(row_data.get("yellow_building_count", 0))
        )
        m_col4.metric(
            "Usable Area %", f"{round(row_data.get('usable_area_percent', 0), 1)}%"
        )

        st.divider()

        st.markdown("**Selected Modeling Features:**")

        available_cols = [col for col in ALL_COLS if col in row_data.index]
        display_data = row_data[available_cols].to_dict()

        df_display = pd.DataFrame(
            list(display_data.items()), columns=["Feature", "Value"]
        )
        df_display["Value"] = df_display["Value"].apply(
            lambda x: round(x, 4) if isinstance(x, float) else x
        )

        st.dataframe(df_display, use_container_width=True, hide_index=True)
